# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('CountryCode', models.CharField(blank=True, max_length=50)),
                ('District', models.CharField(blank=True, max_length=50)),
                ('Population', models.IntegerField()),
            ],
        ),
    ]
