# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=7)),
                ('mobileno', models.IntegerField()),
            ],
        ),
    ]
