# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldsearch', '0002_siteusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('otpnumber', models.IntegerField()),
            ],
        ),
    ]
